"use client";

import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";

export default function RobotsGeneratorClient() {
  const [domain, setDomain] = useState("");
  const [userAgent, setUserAgent] = useState("*");
  const [blockAdmin, setBlockAdmin] = useState(true);
  const [blockPrivate, setBlockPrivate] = useState(false);
  const [blockAll, setBlockAll] = useState(false);
  const [crawlDelay, setCrawlDelay] = useState("");
  const [customDisallow, setCustomDisallow] = useState("");
  const [includeHost, setIncludeHost] = useState(false);
  const [generated, setGenerated] = useState(
    `# robots.txt generated by Shopyor
User-agent: *
Allow: /

Sitemap: https://example.com/sitemap.xml`,
  );

  const cleanDomain = (value) => {
    return value
      .replace("https://", "")
      .replace("http://", "")
      .replace("www.", "")
      .replace("/", "");
  };

  const generateFile = () => {
    let content = `# robots.txt generated by Shopyor\n`;

    content += `User-agent: ${userAgent}\n`;

    if (blockAll) {
      content += "Disallow: /\n";
    } else {
      content += "Allow: /\n";

      if (blockAdmin) content += "Disallow: /admin/\n";
      if (blockPrivate) content += "Disallow: /private/\n";

      const paths = customDisallow.split("\n");

      paths.forEach((path) => {
        if (path.trim()) {
          content += `Disallow: ${path.trim()}\n`;
        }
      });
    }

    if (crawlDelay) {
      content += `Crawl-delay: ${crawlDelay}\n`;
    }

    const d = cleanDomain(domain);

    if (includeHost && d) {
      content += `Host: https://${d}\n`;
    }

    if (d) {
      content += `\nSitemap: https://${d}/sitemap.xml`;
    }

    setGenerated(content);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generated);
  };

  const downloadFile = () => {
    const blob = new Blob([generated], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "robots.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const openTester = () => {
    window.open(
      "https://search.google.com/search-console/robots-testing-tool",
      "_blank",
    );
  };

  return (
    <Card className="rounded-2xl shadow-2xl border bg-background">
      <CardContent className="p-10 space-y-8">
        {/* Domain */}
        <div>
          <Label>Website Domain</Label>
          <Input
            placeholder="example.com"
            value={domain}
            onChange={(e) => setDomain(e.target.value)}
          />
        </div>

        {/* User Agent */}
        <div className="">
          <Label>User Agent</Label>
          <select
            className="bg-card/70 dark:bg-muted/40 text-card-foreground  w-full border rounded-md p-2 mt-2"
            value={userAgent}
            onChange={(e) => setUserAgent(e.target.value)}
          >
            <option value="*">All Crawlers</option>
            <option value="Googlebot">Googlebot</option>
            <option value="Bingbot">Bingbot</option>
          </select>
        </div>

        {/* Switch Options */}
        <div className="flex justify-between items-center">
          <Label>Disallow /admin/</Label>
          <Switch checked={blockAdmin} onCheckedChange={setBlockAdmin} />
        </div>

        <div className="flex justify-between items-center">
          <Label>Disallow /private/</Label>
          <Switch checked={blockPrivate} onCheckedChange={setBlockPrivate} />
        </div>

        <div className="flex justify-between items-center">
          <Label>Block All Search Engines</Label>
          <Switch checked={blockAll} onCheckedChange={setBlockAll} />
        </div>

        {/* Custom Paths */}
        <Textarea
          placeholder={
            "Forexample write different pages which you dont want to crawl \n/login\n/cart\n/checkout"
          }
          value={customDisallow}
          onChange={(e) => setCustomDisallow(e.target.value)}
          className="whitespace-pre-wrap"
        />

        {/* Crawl Delay */}
        <div>
          <Label>Crawl Delay (seconds)</Label>
          <Input
            placeholder="Example: 5"
            value={crawlDelay}
            onChange={(e) => setCrawlDelay(e.target.value)}
          />
        </div>

        {/* Host */}
        <div className="flex justify-between items-center">
          <Label>Include Host Directive</Label>
          <Switch checked={includeHost} onCheckedChange={setIncludeHost} />
        </div>

        {/* Generate Button */}
        <Button onClick={generateFile} className="w-full text-lg">
          Generate Robots.txt
        </Button>

        {/* Output */}
        {generated && (
          <div className="space-y-4">
            <Textarea
              value={generated}
              readOnly
              rows={10}
              className="font-mono"
            />

            <div className="flex flex-col gap-4">
              <Button variant="secondary" onClick={copyToClipboard}>
                Copy
              </Button>

              <Button onClick={downloadFile}>Download robots.txt</Button>

              <Button variant="outline" onClick={openTester}>
                Test in Google Robots Tester
              </Button>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
