"use client";

import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";

export default function RobotsGeneratorClient() {
  const [domain, setDomain] = useState("");
  const [userAgent, setUserAgent] = useState("*");
  const [blockAdmin, setBlockAdmin] = useState(true);
  const [blockPrivate, setBlockPrivate] = useState(false);
  const [blockAll, setBlockAll] = useState(false);
  const [crawlDelay, setCrawlDelay] = useState("");
  const [customDisallow, setCustomDisallow] = useState("");
  const [customAllow, setCustomAllow] = useState("");
  const [includeHost, setIncludeHost] = useState(false);
  const [sitemapUrls, setSitemapUrls] = useState([""]);
  const [generated, setGenerated] = useState("");
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState("basic");
  const [savedConfigs, setSavedConfigs] = useState([]);
  const [configName, setConfigName] = useState("");

  // Load saved configs on mount
  useEffect(() => {
    const saved = localStorage.getItem("robots-configs");
    if (saved) {
      setSavedConfigs(JSON.parse(saved));
    }
    generateFile(); // Generate default
  }, []);

  const cleanDomain = useCallback((value) => {
    if (!value) return "";
    return value
      .replace(/^https?:\/\//, "")
      .replace(/^www\./, "")
      .replace(/\/.*$/, "")
      .toLowerCase();
  }, []);

  const generateFile = useCallback(() => {
    let content = `# robots.txt generated by Shopyor\n`;
    content += `# Created: ${new Date().toLocaleString()}\n\n`;

    // Main user-agent block
    content += `User-agent: ${userAgent}\n`;

    if (blockAll) {
      content += "Disallow: /\n";
    } else {
      content += "Allow: /\n";

      // Common SEO best practices - allow important resources
      content += "Allow: /*.js$\n";
      content += "Allow: /*.css$\n";
      content += "Allow: /*.png$\n";
      content += "Allow: /*.jpg$\n";
      content += "Allow: /*.svg$\n";

      // Block sensitive areas
      if (blockAdmin) content += "Disallow: /admin/\n";
      if (blockPrivate) content += "Disallow: /private/\n";

      // Common paths to block
      content += "Disallow: /cgi-bin/\n";
      content += "Disallow: /tmp/\n";
      content += "Disallow: /logs/\n";

      // Custom disallow paths
      const customPaths = customDisallow.split("\n");
      customPaths.forEach((path) => {
        if (path.trim()) {
          content += `Disallow: ${path.trim()}\n`;
        }
      });

      // Custom allow paths
      const allowPaths = customAllow.split("\n");
      allowPaths.forEach((path) => {
        if (path.trim()) {
          content += `Allow: ${path.trim()}\n`;
        }
      });
    }

    // Crawl delay
    if (crawlDelay && !blockAll) {
      const delay = parseFloat(crawlDelay);
      if (!isNaN(delay) && delay > 0 && delay <= 30) {
        content += `Crawl-delay: ${delay}\n`;
      }
    }

    // Host directive
    const cleanDom = cleanDomain(domain);
    if (includeHost && cleanDom) {
      content += `Host: https://${cleanDom}\n`;
    }

    // Sitemaps
    const validSitemaps = sitemapUrls.filter((url) => url.trim());
    if (validSitemaps.length > 0 && cleanDom) {
      validSitemaps.forEach((sitemap) => {
        if (sitemap.startsWith("http")) {
          content += `\nSitemap: ${sitemap.trim()}`;
        } else {
          content += `\nSitemap: https://${cleanDom}${sitemap.trim()}`;
        }
      });
    } else if (cleanDom) {
      content += `\nSitemap: https://${cleanDom}/sitemap.xml`;
    }

    // Additional directives for specific bots
    if (userAgent === "*") {
      content += `\n\n# Googlebot specific rules\n`;
      content += `User-agent: Googlebot\n`;
      content += `Allow: /\n`;
      if (!blockAll) {
        content += `Crawl-delay: ${crawlDelay || "1"}\n`;
      }

      content += `\n# Bingbot specific rules\n`;
      content += `User-agent: Bingbot\n`;
      content += `Allow: /\n`;
    }

    setGenerated(content);
  }, [
    userAgent,
    blockAll,
    blockAdmin,
    blockPrivate,
    customDisallow,
    customAllow,
    crawlDelay,
    includeHost,
    domain,
    cleanDomain,
    sitemapUrls,
  ]);

  useEffect(() => {
    generateFile();
  }, [generateFile]);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(generated);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const downloadFile = () => {
    const blob = new Blob([generated], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `robots-${cleanDomain(domain) || "file"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const openTester = () => {
    if (domain) {
      const cleanDom = cleanDomain(domain);
      window.open(
        `https://search.google.com/search-console/robots-testing-tool?resource_url=https://${cleanDom}`,
        "_blank",
      );
    } else {
      alert("Please enter your domain first");
    }
  };

  const saveConfiguration = () => {
    if (!configName.trim()) {
      alert("Please enter a configuration name");
      return;
    }

    const config = {
      id: Date.now(),
      name: configName,
      domain,
      userAgent,
      blockAdmin,
      blockPrivate,
      blockAll,
      crawlDelay,
      customDisallow,
      customAllow,
      includeHost,
      sitemapUrls,
    };

    const updated = [...savedConfigs, config];
    setSavedConfigs(updated);
    localStorage.setItem("robots-configs", JSON.stringify(updated));
    setConfigName("");
    alert("Configuration saved!");
  };

  const loadConfiguration = (config) => {
    setDomain(config.domain);
    setUserAgent(config.userAgent);
    setBlockAdmin(config.blockAdmin);
    setBlockPrivate(config.blockPrivate);
    setBlockAll(config.blockAll);
    setCrawlDelay(config.crawlDelay);
    setCustomDisallow(config.customDisallow);
    setCustomAllow(config.customAllow);
    setIncludeHost(config.includeHost);
    setSitemapUrls(config.sitemapUrls);
  };

  const deleteConfiguration = (id) => {
    const updated = savedConfigs.filter((c) => c.id !== id);
    setSavedConfigs(updated);
    localStorage.setItem("robots-configs", JSON.stringify(updated));
  };

  const addSitemap = () => {
    setSitemapUrls([...sitemapUrls, ""]);
  };

  const updateSitemap = (index, value) => {
    const updated = [...sitemapUrls];
    updated[index] = value;
    setSitemapUrls(updated);
  };

  const removeSitemap = (index) => {
    const updated = sitemapUrls.filter((_, i) => i !== index);
    setSitemapUrls(updated);
  };

  return (
    <div className="space-y-6">
      {/* Saved Configurations */}
      {savedConfigs.length > 0 && (
        <div className="bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-950/30 dark:to-purple-950/30 rounded-xl p-4 border border-blue-200 dark:border-blue-800">
          <h3 className="text-sm font-semibold mb-2">
            📁 Saved Configurations
          </h3>
          <div className="flex flex-wrap gap-2">
            {savedConfigs.map((config) => (
              <div
                key={config.id}
                className="flex items-center gap-2 bg-white dark:bg-slate-800 rounded-lg px-3 py-1 shadow-sm"
              >
                <button
                  onClick={() => loadConfiguration(config)}
                  className="text-sm hover:text-blue-600 transition-colors"
                >
                  {config.name}
                </button>
                <button
                  onClick={() => deleteConfiguration(config.id)}
                  className="text-red-500 hover:text-red-700 text-xs"
                >
                  ✕
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Main Card */}
      <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-2xl border border-slate-200 dark:border-slate-700 overflow-hidden">
        {/* Tabs */}
        <div className="border-b border-slate-200 dark:border-slate-700">
          <div className="flex px-6 gap-1">
            {["basic", "advanced", "sitemaps"].map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-4 py-3 text-sm font-medium transition-all relative ${
                  activeTab === tab
                    ? "text-blue-600 dark:text-blue-400"
                    : "text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200"
                }`}
              >
                {tab.charAt(0).toUpperCase() + tab.slice(1)}
                {activeTab === tab && (
                  <motion.div
                    layoutId="activeTab"
                    className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-600"
                  />
                )}
              </button>
            ))}
          </div>
        </div>

        <div className="p-6 md:p-8">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeTab}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
              className="space-y-6"
            >
              {/* Basic Tab */}
              {activeTab === "basic" && (
                <>
                  <div>
                    <label className="block text-sm font-semibold mb-2">
                      Website Domain *
                    </label>
                    <input
                      type="text"
                      placeholder="example.com"
                      value={domain}
                      onChange={(e) => setDomain(e.target.value)}
                      className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition"
                    />
                    <p className="text-xs text-slate-500 mt-1">
                      Enter your domain without https:// or www
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-semibold mb-2">
                      User Agent
                    </label>
                    <select
                      value={userAgent}
                      onChange={(e) => setUserAgent(e.target.value)}
                      className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="*">All Crawlers (*)</option>
                      <option value="Googlebot">Googlebot</option>
                      <option value="Bingbot">Bingbot</option>
                      <option value="Slurp">Yahoo Slurp</option>
                      <option value="DuckDuckBot">DuckDuckGo</option>
                      <option value="Baiduspider">Baiduspider</option>
                      <option value="YandexBot">Yandex Bot</option>
                    </select>
                  </div>

                  <div className="space-y-3">
                    <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-700/30 rounded-lg">
                      <label className="font-medium cursor-pointer">
                        Block All Search Engines
                      </label>
                      <button
                        onClick={() => setBlockAll(!blockAll)}
                        className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                          blockAll
                            ? "bg-red-600"
                            : "bg-slate-300 dark:bg-slate-600"
                        }`}
                      >
                        <span
                          className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                            blockAll ? "translate-x-6" : "translate-x-1"
                          }`}
                        />
                      </button>
                    </div>

                    {!blockAll && (
                      <>
                        <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-700/30 rounded-lg">
                          <label className="font-medium cursor-pointer">
                            Disallow /admin/
                          </label>
                          <button
                            onClick={() => setBlockAdmin(!blockAdmin)}
                            className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                              blockAdmin
                                ? "bg-blue-600"
                                : "bg-slate-300 dark:bg-slate-600"
                            }`}
                          >
                            <span
                              className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                                blockAdmin ? "translate-x-6" : "translate-x-1"
                              }`}
                            />
                          </button>
                        </div>

                        <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-700/30 rounded-lg">
                          <label className="font-medium cursor-pointer">
                            Disallow /private/
                          </label>
                          <button
                            onClick={() => setBlockPrivate(!blockPrivate)}
                            className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                              blockPrivate
                                ? "bg-blue-600"
                                : "bg-slate-300 dark:bg-slate-600"
                            }`}
                          >
                            <span
                              className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                                blockPrivate ? "translate-x-6" : "translate-x-1"
                              }`}
                            />
                          </button>
                        </div>
                      </>
                    )}
                  </div>

                  <div>
                    <label className="block text-sm font-semibold mb-2">
                      Crawl Delay (seconds)
                    </label>
                    <input
                      type="number"
                      step="0.5"
                      min="0"
                      max="30"
                      placeholder="Recommended: 1-5 seconds"
                      value={crawlDelay}
                      onChange={(e) => setCrawlDelay(e.target.value)}
                      className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 focus:ring-2 focus:ring-blue-500"
                    />
                    <p className="text-xs text-slate-500 mt-1">
                      Helps reduce server load by controlling crawl rate
                    </p>
                  </div>
                </>
              )}

              {/* Advanced Tab */}
              {activeTab === "advanced" && (
                <>
                  <div>
                    <label className="block text-sm font-semibold mb-2">
                      Custom Disallow Paths (one per line)
                    </label>
                    <textarea
                      placeholder="/temp/
/includes/
/backup/
?utm_*
?ref=*"
                      rows={5}
                      value={customDisallow}
                      onChange={(e) => setCustomDisallow(e.target.value)}
                      className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 focus:ring-2 focus:ring-blue-500 font-mono text-sm"
                    />
                    <p className="text-xs text-slate-500 mt-1">
                      Use * for wildcards, one path per line
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-semibold mb-2">
                      Custom Allow Paths (one per line)
                    </label>
                    <textarea
                      placeholder="/blog/
/products/
/api/*.json$"
                      rows={5}
                      value={customAllow}
                      onChange={(e) => setCustomAllow(e.target.value)}
                      className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 focus:ring-2 focus:ring-blue-500 font-mono text-sm"
                    />
                    <p className="text-xs text-slate-500 mt-1">
                      Override disallow rules for specific paths
                    </p>
                  </div>

                  <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-700/30 rounded-lg">
                    <div>
                      <label className="font-medium cursor-pointer">
                        Include Host Directive
                      </label>
                      <p className="text-xs text-slate-500">
                        Helps search engines determine the preferred domain
                      </p>
                    </div>
                    <button
                      onClick={() => setIncludeHost(!includeHost)}
                      className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                        includeHost
                          ? "bg-blue-600"
                          : "bg-slate-300 dark:bg-slate-600"
                      }`}
                    >
                      <span
                        className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                          includeHost ? "translate-x-6" : "translate-x-1"
                        }`}
                      />
                    </button>
                  </div>

                  <div className="bg-blue-50 dark:bg-blue-950/30 rounded-lg p-4 border border-blue-200 dark:border-blue-800">
                    <h4 className="font-semibold text-sm mb-2">💡 Pro Tip</h4>
                    <p className="text-sm text-slate-600 dark:text-slate-300">
                      Use custom disallow rules to block duplicate content,
                      parameter-based URLs, or temporary directories. Always
                      test your rules with Google's Robots Testing Tool.
                    </p>
                  </div>
                </>
              )}

              {/* Sitemaps Tab */}
              {activeTab === "sitemaps" && (
                <>
                  <div className="space-y-3">
                    <div className="flex justify-between items-center">
                      <label className="block text-sm font-semibold">
                        Sitemap URLs
                      </label>
                      <button
                        onClick={addSitemap}
                        className="text-sm bg-blue-600 hover:bg-blue-700 text-white px-3 py-1 rounded-lg transition"
                      >
                        + Add Sitemap
                      </button>
                    </div>

                    {sitemapUrls.map((url, index) => (
                      <div key={index} className="flex gap-2">
                        <input
                          type="text"
                          placeholder="/sitemap.xml or https://example.com/sitemap.xml"
                          value={url}
                          onChange={(e) => updateSitemap(index, e.target.value)}
                          className="flex-1 px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 focus:ring-2 focus:ring-blue-500"
                        />
                        {sitemapUrls.length > 1 && (
                          <button
                            onClick={() => removeSitemap(index)}
                            className="px-3 bg-red-100 dark:bg-red-900/30 text-red-600 rounded-lg hover:bg-red-200 transition"
                          >
                            ✕
                          </button>
                        )}
                      </div>
                    ))}

                    <p className="text-xs text-slate-500 mt-2">
                      You can specify multiple sitemaps. Use relative or
                      absolute URLs.
                    </p>
                  </div>

                  <div className="bg-purple-50 dark:bg-purple-950/30 rounded-lg p-4 border border-purple-200 dark:border-purple-800">
                    <h4 className="font-semibold text-sm mb-2">
                      📊 Why Multiple Sitemaps?
                    </h4>
                    <p className="text-sm text-slate-600 dark:text-slate-300">
                      Large websites benefit from having separate sitemaps for
                      different content types (pages, posts, products, images,
                      videos). This helps search engines understand your site
                      structure better.
                    </p>
                  </div>
                </>
              )}
            </motion.div>
          </AnimatePresence>

          {/* Generate Button */}
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={generateFile}
            className="w-full mt-6 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white font-semibold py-3 px-6 rounded-xl transition-all shadow-lg"
          >
            ✨ Generate Robots.txt File
          </motion.button>

          {/* Output Section */}
          {generated && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-4 mt-6"
            >
              <div className="bg-slate-900 dark:bg-slate-950 rounded-xl p-4 border border-slate-700">
                <div className="flex justify-between items-center mb-2">
                  <h3 className="text-sm font-semibold text-slate-300">
                    Generated robots.txt
                  </h3>
                  <div className="flex gap-2">
                    <button
                      onClick={copyToClipboard}
                      className="text-xs bg-slate-700 hover:bg-slate-600 text-white px-3 py-1 rounded transition"
                    >
                      {copied ? "✓ Copied!" : "📋 Copy"}
                    </button>
                    <button
                      onClick={downloadFile}
                      className="text-xs bg-green-600 hover:bg-green-700 text-white px-3 py-1 rounded transition"
                    >
                      💾 Download
                    </button>
                  </div>
                </div>
                <pre className="text-xs font-mono text-green-400 overflow-x-auto whitespace-pre-wrap">
                  {generated}
                </pre>
              </div>

              <div className="flex gap-3">
                <button
                  onClick={openTester}
                  className="flex-1 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 text-slate-700 dark:text-slate-200 font-medium py-2 px-4 rounded-lg transition"
                >
                  🔍 Test in Google Tool
                </button>

                <button
                  onClick={saveConfiguration}
                  className="flex-1 bg-purple-100 dark:bg-purple-900/30 hover:bg-purple-200 dark:hover:bg-purple-900/50 text-purple-700 dark:text-purple-300 font-medium py-2 px-4 rounded-lg transition"
                >
                  💾 Save Configuration
                </button>
              </div>

              {savedConfigs.length > 0 && (
                <div className="flex gap-2">
                  <input
                    type="text"
                    placeholder="Configuration name"
                    value={configName}
                    onChange={(e) => setConfigName(e.target.value)}
                    className="flex-1 px-3 py-2 text-sm rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900"
                  />
                </div>
              )}
            </motion.div>
          )}
        </div>
      </div>

      {/* Usage Stats */}
      <div className="bg-gradient-to-r from-blue-500/10 to-purple-500/10 rounded-xl p-4 text-center">
        <div className="grid grid-cols-3 gap-4">
          <div>
            <div className="text-2xl font-bold text-blue-600">10K+</div>
            <div className="text-xs text-slate-600 dark:text-slate-400">
              Files Generated
            </div>
          </div>
          <div>
            <div className="text-2xl font-bold text-purple-600">4.9</div>
            <div className="text-xs text-slate-600 dark:text-slate-400">
              User Rating
            </div>
          </div>
          <div>
            <div className="text-2xl font-bold text-green-600">100%</div>
            <div className="text-xs text-slate-600 dark:text-slate-400">
              Free Forever
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
